#############################################################################
# Makefile for building: myQmlOsg.app/Contents/MacOS/myQmlOsg
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  myQmlOsg.pro
# Template: app
# Command: /Users/whisperchi/Qt5.7.1/5.7/clang_64/bin/qmake -spec macx-clang CONFIG+=x86_64 -o Makefile myQmlOsg.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -O2 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -O2 -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/include -I../../../Qt5.7.1/5.7/clang_64/lib/QtQuick.framework/Headers -I../../../Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers -I../../../Qt5.7.1/5.7/clang_64/lib/QtQml.framework/Headers -I../../../Qt5.7.1/5.7/clang_64/lib/QtNetwork.framework/Headers -I../../../Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../Qt5.7.1/5.7/clang_64/mkspecs/macx-clang -F/Users/whisperchi/Qt5.7.1/5.7/clang_64/lib
QMAKE         = /Users/whisperchi/Qt5.7.1/5.7/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = myQmlOsg1.0.0
DISTDIR = /Users/whisperchi/recent/Qt/myQmlOsg/.tmp/myQmlOsg1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wl,-rpath,/Users/whisperchi/Qt5.7.1/5.7/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/whisperchi/Qt5.7.1/5.7/clang_64/lib -L/usr/local/lib -losg -losgGA -losgViewer -lOpenThreads -losgText -losgDB -framework QtQuick -framework QtQml -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit -framework QtGui -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		GlobeOsg.cpp \
		osgQuickNode.cpp moc_GlobeOsg.cpp
OBJECTS       = main.o \
		GlobeOsg.o \
		osgQuickNode.o \
		moc_GlobeOsg.o
DIST          = main.qml \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/qdevice.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/device_config.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/common/unix.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/common/mac.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/common/macx.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/common/clang.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/qconfig.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/toolchain.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/default_post.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/qt.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/resources.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/moc.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/yacc.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/lex.prf \
		myQmlOsg.pro GlobeOsg.h \
		osgQuickNode.h \
		osgQuickNode.h main.cpp \
		GlobeOsg.cpp \
		osgQuickNode.cpp
QMAKE_TARGET  = myQmlOsg
DESTDIR       = 
TARGET        = myQmlOsg.app/Contents/MacOS/myQmlOsg


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d myQmlOsg.app/Contents/MacOS/ || mkdir -p myQmlOsg.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: myQmlOsg.pro ../../../Qt5.7.1/5.7/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt5.7.1/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/qdevice.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/device_config.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/common/unix.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/common/mac.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/common/macx.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/common/clang.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/qconfig.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/toolchain.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/default_post.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/qt.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/resources.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/moc.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/yacc.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/lex.prf \
		myQmlOsg.pro \
		../../../Qt5.7.1/5.7/clang_64/lib/QtQuick.framework/QtQuick.prl \
		../../../Qt5.7.1/5.7/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../Qt5.7.1/5.7/clang_64/lib/QtQml.framework/QtQml.prl \
		../../../Qt5.7.1/5.7/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		../../../Qt5.7.1/5.7/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile myQmlOsg.pro
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/qdevice.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/device_config.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/common/unix.conf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/common/mac.conf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/common/macx.conf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/common/sanitize.conf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/common/clang.conf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/qconfig.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/qt_config.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/toolchain.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/toolchain.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/default_pre.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/default_post.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/warn_on.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/qt.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/resources.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/moc.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/file_copies.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/exceptions.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/yacc.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/lex.prf:
myQmlOsg.pro:
../../../Qt5.7.1/5.7/clang_64/lib/QtQuick.framework/QtQuick.prl:
../../../Qt5.7.1/5.7/clang_64/lib/QtGui.framework/QtGui.prl:
../../../Qt5.7.1/5.7/clang_64/lib/QtQml.framework/QtQml.prl:
../../../Qt5.7.1/5.7/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
../../../Qt5.7.1/5.7/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile myQmlOsg.pro

qmake_all: FORCE

myQmlOsg.app/Contents/PkgInfo: 
	@test -d myQmlOsg.app/Contents || mkdir -p myQmlOsg.app/Contents
	@$(DEL_FILE) myQmlOsg.app/Contents/PkgInfo
	@echo "APPL????" > myQmlOsg.app/Contents/PkgInfo
myQmlOsg.app/Contents/Resources/empty.lproj: 
	@test -d myQmlOsg.app/Contents/Resources || mkdir -p myQmlOsg.app/Contents/Resources
	@touch myQmlOsg.app/Contents/Resources/empty.lproj
	
myQmlOsg.app/Contents/Info.plist: 
	@test -d myQmlOsg.app/Contents || mkdir -p myQmlOsg.app/Contents
	@$(DEL_FILE) myQmlOsg.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,WhisperChi.myQmlOsg,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,myQmlOsg,g" -e "s,@LIBRARY@,myQmlOsg,g" -e "s,@TYPEINFO@,????,g" ../../../Qt5.7.1/5.7/clang_64/mkspecs/macx-clang/Info.plist.app >myQmlOsg.app/Contents/Info.plist

all: Makefile \
		myQmlOsg.app/Contents/PkgInfo \
		myQmlOsg.app/Contents/Resources/empty.lproj \
		myQmlOsg.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents GlobeOsg.h osgQuickNode.h osgQuickNode.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp GlobeOsg.cpp osgQuickNode.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r myQmlOsg.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_GlobeOsg.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_GlobeOsg.cpp
moc_GlobeOsg.cpp: ../../../Qt5.7.1/5.7/clang_64/lib/QtQuick.framework/Headers/QQuickItem \
		../../../Qt5.7.1/5.7/clang_64/lib/QtQuick.framework/Headers/qquickitem.h \
		../../../Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLShaderProgram \
		../../../Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		/usr/local/include/osgViewer/Viewer \
		/usr/local/include/osg/ArgumentParser \
		/usr/local/include/osg/Export \
		/usr/local/include/osg/Config \
		/usr/local/include/osg/ref_ptr \
		/usr/local/include/osg/ApplicationUsage \
		/usr/local/include/osg/Referenced \
		/usr/local/include/OpenThreads/ScopedLock \
		/usr/local/include/OpenThreads/Mutex \
		/usr/local/include/OpenThreads/Exports \
		/usr/local/include/OpenThreads/Config \
		/usr/local/include/OpenThreads/Atomic \
		/usr/local/include/osgGA/EventVisitor \
		/usr/local/include/osg/NodeVisitor \
		/usr/local/include/osg/Node \
		/usr/local/include/osg/Object \
		/usr/local/include/osg/CopyOp \
		/usr/local/include/osg/Notify \
		/usr/local/include/osg/StateSet \
		/usr/local/include/osg/StateAttribute \
		/usr/local/include/osg/Callback \
		/usr/local/include/osg/UserDataContainer \
		/usr/local/include/osg/Shader \
		/usr/local/include/osg/GLExtensions \
		/usr/local/include/osg/GLDefines \
		/usr/local/include/osg/GL \
		/usr/local/include/osg/Types \
		/usr/local/include/osg/buffered_value \
		/usr/local/include/osg/DisplaySettings \
		/usr/local/include/osg/Matrixd \
		/usr/local/include/osg/Vec3d \
		/usr/local/include/osg/Vec2d \
		/usr/local/include/osg/Vec2f \
		/usr/local/include/osg/Math \
		/usr/local/include/osg/Vec3f \
		/usr/local/include/osg/Vec4d \
		/usr/local/include/osg/Vec4f \
		/usr/local/include/osg/Quat \
		/usr/local/include/osg/Uniform \
		/usr/local/include/osg/Array \
		/usr/local/include/osg/MixinVector \
		/usr/local/include/osg/Vec2b \
		/usr/local/include/osg/Vec3b \
		/usr/local/include/osg/Vec4b \
		/usr/local/include/osg/Vec2s \
		/usr/local/include/osg/Vec3s \
		/usr/local/include/osg/Vec4s \
		/usr/local/include/osg/Vec2i \
		/usr/local/include/osg/Vec3i \
		/usr/local/include/osg/Vec4i \
		/usr/local/include/osg/Vec2ub \
		/usr/local/include/osg/Vec3ub \
		/usr/local/include/osg/Vec4ub \
		/usr/local/include/osg/Vec3 \
		/usr/local/include/osg/Vec2us \
		/usr/local/include/osg/Vec3us \
		/usr/local/include/osg/Vec4us \
		/usr/local/include/osg/Vec2ui \
		/usr/local/include/osg/Vec3ui \
		/usr/local/include/osg/Vec4ui \
		/usr/local/include/osg/Vec2 \
		/usr/local/include/osg/Vec4 \
		/usr/local/include/osg/Matrix \
		/usr/local/include/osg/Matrixf \
		/usr/local/include/osg/BufferObject \
		/usr/local/include/osg/FrameStamp \
		/usr/local/include/osg/BoundingSphere \
		/usr/local/include/osg/BoundingBox \
		/usr/local/include/osg/Geode \
		/usr/local/include/osg/Drawable \
		/usr/local/include/osg/Shape \
		/usr/local/include/osg/Plane \
		/usr/local/include/osg/PrimitiveSet \
		/usr/local/include/osg/RenderInfo \
		/usr/local/include/osg/State \
		/usr/local/include/osg/Observer \
		/usr/local/include/osg/Timer \
		/usr/local/include/osg/ShaderComposer \
		/usr/local/include/osg/Program \
		/usr/local/include/osg/Polytope \
		/usr/local/include/osg/fast_back_stack \
		/usr/local/include/osg/Viewport \
		/usr/local/include/osg/GLBeginEndAdapter \
		/usr/local/include/osg/ArrayDispatchers \
		/usr/local/include/osg/GraphicsCostEstimator \
		/usr/local/include/osg/View \
		/usr/local/include/osg/Camera \
		/usr/local/include/osg/Transform \
		/usr/local/include/osg/Group \
		/usr/local/include/osg/ColorMask \
		/usr/local/include/osg/CullSettings \
		/usr/local/include/osg/ClearNode \
		/usr/local/include/osg/Texture \
		/usr/local/include/osg/Image \
		/usr/local/include/osg/GraphicsContext \
		/usr/local/include/osg/GraphicsThread \
		/usr/local/include/osg/OperationThread \
		/usr/local/include/osg/observer_ptr \
		/usr/local/include/OpenThreads/Thread \
		/usr/local/include/OpenThreads/Barrier \
		/usr/local/include/OpenThreads/Condition \
		/usr/local/include/OpenThreads/Block \
		/usr/local/include/osg/Stats \
		/usr/local/include/osg/Light \
		/usr/local/include/osg/Billboard \
		/usr/local/include/osg/LOD \
		/usr/local/include/osg/Switch \
		/usr/local/include/osg/LightSource \
		/usr/local/include/osg/Projection \
		/usr/local/include/osg/OccluderNode \
		/usr/local/include/osg/ConvexPlanarOccluder \
		/usr/local/include/osg/ConvexPlanarPolygon \
		/usr/local/include/osg/ScriptEngine \
		/usr/local/include/osgGA/GUIEventAdapter \
		/usr/local/include/osgGA/Event \
		/usr/local/include/osgGA/Export \
		/usr/local/include/osgGA/GUIActionAdapter \
		/usr/local/include/osgUtil/LineSegmentIntersector \
		/usr/local/include/osgUtil/IntersectionVisitor \
		/usr/local/include/osgUtil/Export \
		/usr/local/include/osgGA/EventQueue \
		/usr/local/include/osgUtil/UpdateVisitor \
		/usr/local/include/osgViewer/GraphicsWindow \
		/usr/local/include/osgViewer/Export \
		/usr/local/include/osgViewer/View \
		/usr/local/include/osgUtil/PolytopeIntersector \
		/usr/local/include/osgUtil/SceneView \
		/usr/local/include/osg/CollectOccludersVisitor \
		/usr/local/include/osg/CullStack \
		/usr/local/include/osg/CullingSet \
		/usr/local/include/osg/ShadowVolumeOccluder \
		/usr/local/include/osgUtil/CullVisitor \
		/usr/local/include/osgUtil/StateGraph \
		/usr/local/include/osgUtil/RenderLeaf \
		/usr/local/include/osgUtil/RenderStage \
		/usr/local/include/osg/FrameBufferObject \
		/usr/local/include/osgUtil/RenderBin \
		/usr/local/include/osgUtil/PositionalStateContainer \
		/usr/local/include/osgGA/CameraManipulator \
		/usr/local/include/osg/CoordinateSystemNode \
		/usr/local/include/osgGA/GUIEventHandler \
		/usr/local/include/osgGA/EventHandler \
		/usr/local/include/osgGA/Device \
		/usr/local/include/osgViewer/Scene \
		/usr/local/include/osgDB/DatabasePager \
		/usr/local/include/osg/PagedLOD \
		/usr/local/include/osg/ObserverNodePath \
		/usr/local/include/osgUtil/IncrementalCompileOperation \
		/usr/local/include/osgUtil/GLObjectsVisitor \
		/usr/local/include/osg/Geometry \
		/usr/local/include/osgDB/SharedStateManager \
		/usr/local/include/osgDB/Export \
		/usr/local/include/osgDB/ReaderWriter \
		/usr/local/include/osgDB/AuthenticationMap \
		/usr/local/include/osgDB/Options \
		/usr/local/include/osgDB/Callbacks \
		/usr/local/include/osgDB/FileCache \
		/usr/local/include/osgDB/DatabaseRevisions \
		/usr/local/include/osgDB/ObjectCache \
		/usr/local/include/osgDB/ImagePager \
		/usr/local/include/osgViewer/ViewerBase \
		/usr/local/include/osgViewer/Keystone \
		/usr/local/include/osg/PositionAttitudeTransform \
		/usr/local/include/osg/AnimationPath \
		/usr/local/include/osgGA/OrbitManipulator \
		/usr/local/include/osgGA/StandardManipulator \
		GlobeOsg.h \
		../../../Qt5.7.1/5.7/clang_64/bin/moc
	/Users/whisperchi/Qt5.7.1/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/whisperchi/Qt5.7.1/5.7/clang_64/mkspecs/macx-clang -I/Users/whisperchi/recent/Qt/myQmlOsg -I/usr/local/include -I/Users/whisperchi/Qt5.7.1/5.7/clang_64/lib/QtQuick.framework/Headers -I/Users/whisperchi/Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/whisperchi/Qt5.7.1/5.7/clang_64/lib/QtQml.framework/Headers -I/Users/whisperchi/Qt5.7.1/5.7/clang_64/lib/QtNetwork.framework/Headers -I/Users/whisperchi/Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Users/whisperchi/Qt5.7.1/5.7/clang_64/lib GlobeOsg.h -o moc_GlobeOsg.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../../Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers/QGuiApplication \
		../../../Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../../Qt5.7.1/5.7/clang_64/lib/QtQml.framework/Headers/QQmlApplicationEngine \
		../../../Qt5.7.1/5.7/clang_64/lib/QtQml.framework/Headers/qqmlapplicationengine.h \
		GlobeOsg.h \
		../../../Qt5.7.1/5.7/clang_64/lib/QtQuick.framework/Headers/QQuickItem \
		../../../Qt5.7.1/5.7/clang_64/lib/QtQuick.framework/Headers/qquickitem.h \
		../../../Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLShaderProgram \
		../../../Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		/usr/local/include/osgViewer/Viewer \
		/usr/local/include/osg/ArgumentParser \
		/usr/local/include/osg/Export \
		/usr/local/include/osg/Config \
		/usr/local/include/osg/ref_ptr \
		/usr/local/include/osg/ApplicationUsage \
		/usr/local/include/osg/Referenced \
		/usr/local/include/OpenThreads/ScopedLock \
		/usr/local/include/OpenThreads/Mutex \
		/usr/local/include/OpenThreads/Exports \
		/usr/local/include/OpenThreads/Config \
		/usr/local/include/OpenThreads/Atomic \
		/usr/local/include/osgGA/EventVisitor \
		/usr/local/include/osg/NodeVisitor \
		/usr/local/include/osg/Node \
		/usr/local/include/osg/Object \
		/usr/local/include/osg/CopyOp \
		/usr/local/include/osg/Notify \
		/usr/local/include/osg/StateSet \
		/usr/local/include/osg/StateAttribute \
		/usr/local/include/osg/Callback \
		/usr/local/include/osg/UserDataContainer \
		/usr/local/include/osg/Shader \
		/usr/local/include/osg/GLExtensions \
		/usr/local/include/osg/GLDefines \
		/usr/local/include/osg/GL \
		/usr/local/include/osg/Types \
		/usr/local/include/osg/buffered_value \
		/usr/local/include/osg/DisplaySettings \
		/usr/local/include/osg/Matrixd \
		/usr/local/include/osg/Vec3d \
		/usr/local/include/osg/Vec2d \
		/usr/local/include/osg/Vec2f \
		/usr/local/include/osg/Math \
		/usr/local/include/osg/Vec3f \
		/usr/local/include/osg/Vec4d \
		/usr/local/include/osg/Vec4f \
		/usr/local/include/osg/Quat \
		/usr/local/include/osg/Uniform \
		/usr/local/include/osg/Array \
		/usr/local/include/osg/MixinVector \
		/usr/local/include/osg/Vec2b \
		/usr/local/include/osg/Vec3b \
		/usr/local/include/osg/Vec4b \
		/usr/local/include/osg/Vec2s \
		/usr/local/include/osg/Vec3s \
		/usr/local/include/osg/Vec4s \
		/usr/local/include/osg/Vec2i \
		/usr/local/include/osg/Vec3i \
		/usr/local/include/osg/Vec4i \
		/usr/local/include/osg/Vec2ub \
		/usr/local/include/osg/Vec3ub \
		/usr/local/include/osg/Vec4ub \
		/usr/local/include/osg/Vec3 \
		/usr/local/include/osg/Vec2us \
		/usr/local/include/osg/Vec3us \
		/usr/local/include/osg/Vec4us \
		/usr/local/include/osg/Vec2ui \
		/usr/local/include/osg/Vec3ui \
		/usr/local/include/osg/Vec4ui \
		/usr/local/include/osg/Vec2 \
		/usr/local/include/osg/Vec4 \
		/usr/local/include/osg/Matrix \
		/usr/local/include/osg/Matrixf \
		/usr/local/include/osg/BufferObject \
		/usr/local/include/osg/FrameStamp \
		/usr/local/include/osg/BoundingSphere \
		/usr/local/include/osg/BoundingBox \
		/usr/local/include/osg/Geode \
		/usr/local/include/osg/Drawable \
		/usr/local/include/osg/Shape \
		/usr/local/include/osg/Plane \
		/usr/local/include/osg/PrimitiveSet \
		/usr/local/include/osg/RenderInfo \
		/usr/local/include/osg/State \
		/usr/local/include/osg/Observer \
		/usr/local/include/osg/Timer \
		/usr/local/include/osg/ShaderComposer \
		/usr/local/include/osg/Program \
		/usr/local/include/osg/Polytope \
		/usr/local/include/osg/fast_back_stack \
		/usr/local/include/osg/Viewport \
		/usr/local/include/osg/GLBeginEndAdapter \
		/usr/local/include/osg/ArrayDispatchers \
		/usr/local/include/osg/GraphicsCostEstimator \
		/usr/local/include/osg/View \
		/usr/local/include/osg/Camera \
		/usr/local/include/osg/Transform \
		/usr/local/include/osg/Group \
		/usr/local/include/osg/ColorMask \
		/usr/local/include/osg/CullSettings \
		/usr/local/include/osg/ClearNode \
		/usr/local/include/osg/Texture \
		/usr/local/include/osg/Image \
		/usr/local/include/osg/GraphicsContext \
		/usr/local/include/osg/GraphicsThread \
		/usr/local/include/osg/OperationThread \
		/usr/local/include/osg/observer_ptr \
		/usr/local/include/OpenThreads/Thread \
		/usr/local/include/OpenThreads/Barrier \
		/usr/local/include/OpenThreads/Condition \
		/usr/local/include/OpenThreads/Block \
		/usr/local/include/osg/Stats \
		/usr/local/include/osg/Light \
		/usr/local/include/osg/Billboard \
		/usr/local/include/osg/LOD \
		/usr/local/include/osg/Switch \
		/usr/local/include/osg/LightSource \
		/usr/local/include/osg/Projection \
		/usr/local/include/osg/OccluderNode \
		/usr/local/include/osg/ConvexPlanarOccluder \
		/usr/local/include/osg/ConvexPlanarPolygon \
		/usr/local/include/osg/ScriptEngine \
		/usr/local/include/osgGA/GUIEventAdapter \
		/usr/local/include/osgGA/Event \
		/usr/local/include/osgGA/Export \
		/usr/local/include/osgGA/GUIActionAdapter \
		/usr/local/include/osgUtil/LineSegmentIntersector \
		/usr/local/include/osgUtil/IntersectionVisitor \
		/usr/local/include/osgUtil/Export \
		/usr/local/include/osgGA/EventQueue \
		/usr/local/include/osgUtil/UpdateVisitor \
		/usr/local/include/osgViewer/GraphicsWindow \
		/usr/local/include/osgViewer/Export \
		/usr/local/include/osgViewer/View \
		/usr/local/include/osgUtil/PolytopeIntersector \
		/usr/local/include/osgUtil/SceneView \
		/usr/local/include/osg/CollectOccludersVisitor \
		/usr/local/include/osg/CullStack \
		/usr/local/include/osg/CullingSet \
		/usr/local/include/osg/ShadowVolumeOccluder \
		/usr/local/include/osgUtil/CullVisitor \
		/usr/local/include/osgUtil/StateGraph \
		/usr/local/include/osgUtil/RenderLeaf \
		/usr/local/include/osgUtil/RenderStage \
		/usr/local/include/osg/FrameBufferObject \
		/usr/local/include/osgUtil/RenderBin \
		/usr/local/include/osgUtil/PositionalStateContainer \
		/usr/local/include/osgGA/CameraManipulator \
		/usr/local/include/osg/CoordinateSystemNode \
		/usr/local/include/osgGA/GUIEventHandler \
		/usr/local/include/osgGA/EventHandler \
		/usr/local/include/osgGA/Device \
		/usr/local/include/osgViewer/Scene \
		/usr/local/include/osgDB/DatabasePager \
		/usr/local/include/osg/PagedLOD \
		/usr/local/include/osg/ObserverNodePath \
		/usr/local/include/osgUtil/IncrementalCompileOperation \
		/usr/local/include/osgUtil/GLObjectsVisitor \
		/usr/local/include/osg/Geometry \
		/usr/local/include/osgDB/SharedStateManager \
		/usr/local/include/osgDB/Export \
		/usr/local/include/osgDB/ReaderWriter \
		/usr/local/include/osgDB/AuthenticationMap \
		/usr/local/include/osgDB/Options \
		/usr/local/include/osgDB/Callbacks \
		/usr/local/include/osgDB/FileCache \
		/usr/local/include/osgDB/DatabaseRevisions \
		/usr/local/include/osgDB/ObjectCache \
		/usr/local/include/osgDB/ImagePager \
		/usr/local/include/osgViewer/ViewerBase \
		/usr/local/include/osgViewer/Keystone \
		/usr/local/include/osg/PositionAttitudeTransform \
		/usr/local/include/osg/AnimationPath \
		/usr/local/include/osgGA/OrbitManipulator \
		/usr/local/include/osgGA/StandardManipulator
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

GlobeOsg.o: GlobeOsg.cpp GlobeOsg.h \
		../../../Qt5.7.1/5.7/clang_64/lib/QtQuick.framework/Headers/QQuickItem \
		../../../Qt5.7.1/5.7/clang_64/lib/QtQuick.framework/Headers/qquickitem.h \
		../../../Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLShaderProgram \
		../../../Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		/usr/local/include/osgViewer/Viewer \
		/usr/local/include/osg/ArgumentParser \
		/usr/local/include/osg/Export \
		/usr/local/include/osg/Config \
		/usr/local/include/osg/ref_ptr \
		/usr/local/include/osg/ApplicationUsage \
		/usr/local/include/osg/Referenced \
		/usr/local/include/OpenThreads/ScopedLock \
		/usr/local/include/OpenThreads/Mutex \
		/usr/local/include/OpenThreads/Exports \
		/usr/local/include/OpenThreads/Config \
		/usr/local/include/OpenThreads/Atomic \
		/usr/local/include/osgGA/EventVisitor \
		/usr/local/include/osg/NodeVisitor \
		/usr/local/include/osg/Node \
		/usr/local/include/osg/Object \
		/usr/local/include/osg/CopyOp \
		/usr/local/include/osg/Notify \
		/usr/local/include/osg/StateSet \
		/usr/local/include/osg/StateAttribute \
		/usr/local/include/osg/Callback \
		/usr/local/include/osg/UserDataContainer \
		/usr/local/include/osg/Shader \
		/usr/local/include/osg/GLExtensions \
		/usr/local/include/osg/GLDefines \
		/usr/local/include/osg/GL \
		/usr/local/include/osg/Types \
		/usr/local/include/osg/buffered_value \
		/usr/local/include/osg/DisplaySettings \
		/usr/local/include/osg/Matrixd \
		/usr/local/include/osg/Vec3d \
		/usr/local/include/osg/Vec2d \
		/usr/local/include/osg/Vec2f \
		/usr/local/include/osg/Math \
		/usr/local/include/osg/Vec3f \
		/usr/local/include/osg/Vec4d \
		/usr/local/include/osg/Vec4f \
		/usr/local/include/osg/Quat \
		/usr/local/include/osg/Uniform \
		/usr/local/include/osg/Array \
		/usr/local/include/osg/MixinVector \
		/usr/local/include/osg/Vec2b \
		/usr/local/include/osg/Vec3b \
		/usr/local/include/osg/Vec4b \
		/usr/local/include/osg/Vec2s \
		/usr/local/include/osg/Vec3s \
		/usr/local/include/osg/Vec4s \
		/usr/local/include/osg/Vec2i \
		/usr/local/include/osg/Vec3i \
		/usr/local/include/osg/Vec4i \
		/usr/local/include/osg/Vec2ub \
		/usr/local/include/osg/Vec3ub \
		/usr/local/include/osg/Vec4ub \
		/usr/local/include/osg/Vec3 \
		/usr/local/include/osg/Vec2us \
		/usr/local/include/osg/Vec3us \
		/usr/local/include/osg/Vec4us \
		/usr/local/include/osg/Vec2ui \
		/usr/local/include/osg/Vec3ui \
		/usr/local/include/osg/Vec4ui \
		/usr/local/include/osg/Vec2 \
		/usr/local/include/osg/Vec4 \
		/usr/local/include/osg/Matrix \
		/usr/local/include/osg/Matrixf \
		/usr/local/include/osg/BufferObject \
		/usr/local/include/osg/FrameStamp \
		/usr/local/include/osg/BoundingSphere \
		/usr/local/include/osg/BoundingBox \
		/usr/local/include/osg/Geode \
		/usr/local/include/osg/Drawable \
		/usr/local/include/osg/Shape \
		/usr/local/include/osg/Plane \
		/usr/local/include/osg/PrimitiveSet \
		/usr/local/include/osg/RenderInfo \
		/usr/local/include/osg/State \
		/usr/local/include/osg/Observer \
		/usr/local/include/osg/Timer \
		/usr/local/include/osg/ShaderComposer \
		/usr/local/include/osg/Program \
		/usr/local/include/osg/Polytope \
		/usr/local/include/osg/fast_back_stack \
		/usr/local/include/osg/Viewport \
		/usr/local/include/osg/GLBeginEndAdapter \
		/usr/local/include/osg/ArrayDispatchers \
		/usr/local/include/osg/GraphicsCostEstimator \
		/usr/local/include/osg/View \
		/usr/local/include/osg/Camera \
		/usr/local/include/osg/Transform \
		/usr/local/include/osg/Group \
		/usr/local/include/osg/ColorMask \
		/usr/local/include/osg/CullSettings \
		/usr/local/include/osg/ClearNode \
		/usr/local/include/osg/Texture \
		/usr/local/include/osg/Image \
		/usr/local/include/osg/GraphicsContext \
		/usr/local/include/osg/GraphicsThread \
		/usr/local/include/osg/OperationThread \
		/usr/local/include/osg/observer_ptr \
		/usr/local/include/OpenThreads/Thread \
		/usr/local/include/OpenThreads/Barrier \
		/usr/local/include/OpenThreads/Condition \
		/usr/local/include/OpenThreads/Block \
		/usr/local/include/osg/Stats \
		/usr/local/include/osg/Light \
		/usr/local/include/osg/Billboard \
		/usr/local/include/osg/LOD \
		/usr/local/include/osg/Switch \
		/usr/local/include/osg/LightSource \
		/usr/local/include/osg/Projection \
		/usr/local/include/osg/OccluderNode \
		/usr/local/include/osg/ConvexPlanarOccluder \
		/usr/local/include/osg/ConvexPlanarPolygon \
		/usr/local/include/osg/ScriptEngine \
		/usr/local/include/osgGA/GUIEventAdapter \
		/usr/local/include/osgGA/Event \
		/usr/local/include/osgGA/Export \
		/usr/local/include/osgGA/GUIActionAdapter \
		/usr/local/include/osgUtil/LineSegmentIntersector \
		/usr/local/include/osgUtil/IntersectionVisitor \
		/usr/local/include/osgUtil/Export \
		/usr/local/include/osgGA/EventQueue \
		/usr/local/include/osgUtil/UpdateVisitor \
		/usr/local/include/osgViewer/GraphicsWindow \
		/usr/local/include/osgViewer/Export \
		/usr/local/include/osgViewer/View \
		/usr/local/include/osgUtil/PolytopeIntersector \
		/usr/local/include/osgUtil/SceneView \
		/usr/local/include/osg/CollectOccludersVisitor \
		/usr/local/include/osg/CullStack \
		/usr/local/include/osg/CullingSet \
		/usr/local/include/osg/ShadowVolumeOccluder \
		/usr/local/include/osgUtil/CullVisitor \
		/usr/local/include/osgUtil/StateGraph \
		/usr/local/include/osgUtil/RenderLeaf \
		/usr/local/include/osgUtil/RenderStage \
		/usr/local/include/osg/FrameBufferObject \
		/usr/local/include/osgUtil/RenderBin \
		/usr/local/include/osgUtil/PositionalStateContainer \
		/usr/local/include/osgGA/CameraManipulator \
		/usr/local/include/osg/CoordinateSystemNode \
		/usr/local/include/osgGA/GUIEventHandler \
		/usr/local/include/osgGA/EventHandler \
		/usr/local/include/osgGA/Device \
		/usr/local/include/osgViewer/Scene \
		/usr/local/include/osgDB/DatabasePager \
		/usr/local/include/osg/PagedLOD \
		/usr/local/include/osg/ObserverNodePath \
		/usr/local/include/osgUtil/IncrementalCompileOperation \
		/usr/local/include/osgUtil/GLObjectsVisitor \
		/usr/local/include/osg/Geometry \
		/usr/local/include/osgDB/SharedStateManager \
		/usr/local/include/osgDB/Export \
		/usr/local/include/osgDB/ReaderWriter \
		/usr/local/include/osgDB/AuthenticationMap \
		/usr/local/include/osgDB/Options \
		/usr/local/include/osgDB/Callbacks \
		/usr/local/include/osgDB/FileCache \
		/usr/local/include/osgDB/DatabaseRevisions \
		/usr/local/include/osgDB/ObjectCache \
		/usr/local/include/osgDB/ImagePager \
		/usr/local/include/osgViewer/ViewerBase \
		/usr/local/include/osgViewer/Keystone \
		/usr/local/include/osg/PositionAttitudeTransform \
		/usr/local/include/osg/AnimationPath \
		/usr/local/include/osgGA/OrbitManipulator \
		/usr/local/include/osgGA/StandardManipulator \
		osgQuickNode.h \
		../../../Qt5.7.1/5.7/clang_64/lib/QtQuick.framework/Headers/QQuickWindow \
		../../../Qt5.7.1/5.7/clang_64/lib/QtQuick.framework/Headers/qquickwindow.h \
		../../../Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLFunctions \
		../../../Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		../../../Qt5.7.1/5.7/clang_64/lib/QtQuick.framework/Headers/QSGSimpleTextureNode \
		../../../Qt5.7.1/5.7/clang_64/lib/QtQuick.framework/Headers/qsgsimpletexturenode.h \
		/usr/local/include/osg/ShapeDrawable \
		/usr/local/include/osg/PolygonMode \
		/usr/local/include/osgViewer/ViewerEventHandlers \
		/usr/local/include/osgText/Text \
		/usr/local/include/osgText/TextBase \
		/usr/local/include/osgText/String \
		/usr/local/include/osgText/Export \
		/usr/local/include/osgText/KerningType \
		/usr/local/include/osgText/Font \
		/usr/local/include/osg/TexEnv \
		/usr/local/include/osgText/Glyph \
		/usr/local/include/osg/Texture2D \
		/usr/local/include/osgText/Style \
		/usr/local/include/osgGA/AnimationPathManipulator \
		/usr/local/include/osgDB/fstream
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GlobeOsg.o GlobeOsg.cpp

osgQuickNode.o: osgQuickNode.cpp osgQuickNode.h \
		/usr/local/include/osgViewer/Viewer \
		/usr/local/include/osg/ArgumentParser \
		/usr/local/include/osg/Export \
		/usr/local/include/osg/Config \
		/usr/local/include/osg/ref_ptr \
		/usr/local/include/osg/ApplicationUsage \
		/usr/local/include/osg/Referenced \
		/usr/local/include/OpenThreads/ScopedLock \
		/usr/local/include/OpenThreads/Mutex \
		/usr/local/include/OpenThreads/Exports \
		/usr/local/include/OpenThreads/Config \
		/usr/local/include/OpenThreads/Atomic \
		/usr/local/include/osgGA/EventVisitor \
		/usr/local/include/osg/NodeVisitor \
		/usr/local/include/osg/Node \
		/usr/local/include/osg/Object \
		/usr/local/include/osg/CopyOp \
		/usr/local/include/osg/Notify \
		/usr/local/include/osg/StateSet \
		/usr/local/include/osg/StateAttribute \
		/usr/local/include/osg/Callback \
		/usr/local/include/osg/UserDataContainer \
		/usr/local/include/osg/Shader \
		/usr/local/include/osg/GLExtensions \
		/usr/local/include/osg/GLDefines \
		/usr/local/include/osg/GL \
		/usr/local/include/osg/Types \
		/usr/local/include/osg/buffered_value \
		/usr/local/include/osg/DisplaySettings \
		/usr/local/include/osg/Matrixd \
		/usr/local/include/osg/Vec3d \
		/usr/local/include/osg/Vec2d \
		/usr/local/include/osg/Vec2f \
		/usr/local/include/osg/Math \
		/usr/local/include/osg/Vec3f \
		/usr/local/include/osg/Vec4d \
		/usr/local/include/osg/Vec4f \
		/usr/local/include/osg/Quat \
		/usr/local/include/osg/Uniform \
		/usr/local/include/osg/Array \
		/usr/local/include/osg/MixinVector \
		/usr/local/include/osg/Vec2b \
		/usr/local/include/osg/Vec3b \
		/usr/local/include/osg/Vec4b \
		/usr/local/include/osg/Vec2s \
		/usr/local/include/osg/Vec3s \
		/usr/local/include/osg/Vec4s \
		/usr/local/include/osg/Vec2i \
		/usr/local/include/osg/Vec3i \
		/usr/local/include/osg/Vec4i \
		/usr/local/include/osg/Vec2ub \
		/usr/local/include/osg/Vec3ub \
		/usr/local/include/osg/Vec4ub \
		/usr/local/include/osg/Vec3 \
		/usr/local/include/osg/Vec2us \
		/usr/local/include/osg/Vec3us \
		/usr/local/include/osg/Vec4us \
		/usr/local/include/osg/Vec2ui \
		/usr/local/include/osg/Vec3ui \
		/usr/local/include/osg/Vec4ui \
		/usr/local/include/osg/Vec2 \
		/usr/local/include/osg/Vec4 \
		/usr/local/include/osg/Matrix \
		/usr/local/include/osg/Matrixf \
		/usr/local/include/osg/BufferObject \
		/usr/local/include/osg/FrameStamp \
		/usr/local/include/osg/BoundingSphere \
		/usr/local/include/osg/BoundingBox \
		/usr/local/include/osg/Geode \
		/usr/local/include/osg/Drawable \
		/usr/local/include/osg/Shape \
		/usr/local/include/osg/Plane \
		/usr/local/include/osg/PrimitiveSet \
		/usr/local/include/osg/RenderInfo \
		/usr/local/include/osg/State \
		/usr/local/include/osg/Observer \
		/usr/local/include/osg/Timer \
		/usr/local/include/osg/ShaderComposer \
		/usr/local/include/osg/Program \
		/usr/local/include/osg/Polytope \
		/usr/local/include/osg/fast_back_stack \
		/usr/local/include/osg/Viewport \
		/usr/local/include/osg/GLBeginEndAdapter \
		/usr/local/include/osg/ArrayDispatchers \
		/usr/local/include/osg/GraphicsCostEstimator \
		/usr/local/include/osg/View \
		/usr/local/include/osg/Camera \
		/usr/local/include/osg/Transform \
		/usr/local/include/osg/Group \
		/usr/local/include/osg/ColorMask \
		/usr/local/include/osg/CullSettings \
		/usr/local/include/osg/ClearNode \
		/usr/local/include/osg/Texture \
		/usr/local/include/osg/Image \
		/usr/local/include/osg/GraphicsContext \
		/usr/local/include/osg/GraphicsThread \
		/usr/local/include/osg/OperationThread \
		/usr/local/include/osg/observer_ptr \
		/usr/local/include/OpenThreads/Thread \
		/usr/local/include/OpenThreads/Barrier \
		/usr/local/include/OpenThreads/Condition \
		/usr/local/include/OpenThreads/Block \
		/usr/local/include/osg/Stats \
		/usr/local/include/osg/Light \
		/usr/local/include/osg/Billboard \
		/usr/local/include/osg/LOD \
		/usr/local/include/osg/Switch \
		/usr/local/include/osg/LightSource \
		/usr/local/include/osg/Projection \
		/usr/local/include/osg/OccluderNode \
		/usr/local/include/osg/ConvexPlanarOccluder \
		/usr/local/include/osg/ConvexPlanarPolygon \
		/usr/local/include/osg/ScriptEngine \
		/usr/local/include/osgGA/GUIEventAdapter \
		/usr/local/include/osgGA/Event \
		/usr/local/include/osgGA/Export \
		/usr/local/include/osgGA/GUIActionAdapter \
		/usr/local/include/osgUtil/LineSegmentIntersector \
		/usr/local/include/osgUtil/IntersectionVisitor \
		/usr/local/include/osgUtil/Export \
		/usr/local/include/osgGA/EventQueue \
		/usr/local/include/osgUtil/UpdateVisitor \
		/usr/local/include/osgViewer/GraphicsWindow \
		/usr/local/include/osgViewer/Export \
		/usr/local/include/osgViewer/View \
		/usr/local/include/osgUtil/PolytopeIntersector \
		/usr/local/include/osgUtil/SceneView \
		/usr/local/include/osg/CollectOccludersVisitor \
		/usr/local/include/osg/CullStack \
		/usr/local/include/osg/CullingSet \
		/usr/local/include/osg/ShadowVolumeOccluder \
		/usr/local/include/osgUtil/CullVisitor \
		/usr/local/include/osgUtil/StateGraph \
		/usr/local/include/osgUtil/RenderLeaf \
		/usr/local/include/osgUtil/RenderStage \
		/usr/local/include/osg/FrameBufferObject \
		/usr/local/include/osgUtil/RenderBin \
		/usr/local/include/osgUtil/PositionalStateContainer \
		/usr/local/include/osgGA/CameraManipulator \
		/usr/local/include/osg/CoordinateSystemNode \
		/usr/local/include/osgGA/GUIEventHandler \
		/usr/local/include/osgGA/EventHandler \
		/usr/local/include/osgGA/Device \
		/usr/local/include/osgViewer/Scene \
		/usr/local/include/osgDB/DatabasePager \
		/usr/local/include/osg/PagedLOD \
		/usr/local/include/osg/ObserverNodePath \
		/usr/local/include/osgUtil/IncrementalCompileOperation \
		/usr/local/include/osgUtil/GLObjectsVisitor \
		/usr/local/include/osg/Geometry \
		/usr/local/include/osgDB/SharedStateManager \
		/usr/local/include/osgDB/Export \
		/usr/local/include/osgDB/ReaderWriter \
		/usr/local/include/osgDB/AuthenticationMap \
		/usr/local/include/osgDB/Options \
		/usr/local/include/osgDB/Callbacks \
		/usr/local/include/osgDB/FileCache \
		/usr/local/include/osgDB/DatabaseRevisions \
		/usr/local/include/osgDB/ObjectCache \
		/usr/local/include/osgDB/ImagePager \
		/usr/local/include/osgViewer/ViewerBase \
		/usr/local/include/osgViewer/Keystone \
		/usr/local/include/osg/PositionAttitudeTransform \
		/usr/local/include/osg/AnimationPath \
		../../../Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers/QSurfaceFormat \
		../../../Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers/qsurfaceformat.h \
		../../../Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLContext \
		../../../Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		../../../Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLFunctions \
		../../../Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		/usr/local/include/osg/Texture2D \
		/usr/local/include/osg/ShapeDrawable \
		/usr/local/include/osg/PolygonMode \
		/usr/local/include/osgGA/OrbitManipulator \
		/usr/local/include/osgGA/StandardManipulator \
		/usr/local/include/osgViewer/ViewerEventHandlers \
		/usr/local/include/osgText/Text \
		/usr/local/include/osgText/TextBase \
		/usr/local/include/osgText/String \
		/usr/local/include/osgText/Export \
		/usr/local/include/osgText/KerningType \
		/usr/local/include/osgText/Font \
		/usr/local/include/osg/TexEnv \
		/usr/local/include/osgText/Glyph \
		/usr/local/include/osgText/Style \
		/usr/local/include/osgGA/AnimationPathManipulator \
		/usr/local/include/osgDB/fstream \
		/usr/local/include/osg/NodeCallback \
		/usr/local/include/osgDB/ReadFile \
		/usr/local/include/osgDB/Registry \
		/usr/local/include/OpenThreads/ReentrantMutex \
		/usr/local/include/osg/KdTree \
		/usr/local/include/osgDB/DynamicLibrary \
		/usr/local/include/osgDB/DotOsgWrapper \
		/usr/local/include/osgDB/Input \
		/usr/local/include/osgDB/Output \
		/usr/local/include/osgDB/ObjectWrapper \
		/usr/local/include/osgDB/Serializer \
		/usr/local/include/osgDB/InputStream \
		/usr/local/include/osg/Endian \
		/usr/local/include/osgDB/StreamOperator \
		/usr/local/include/osgDB/DataTypes \
		/usr/local/include/osgDB/OutputStream \
		/usr/local/include/osg/Version \
		/usr/local/include/osgDB/ImageProcessor
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o osgQuickNode.o osgQuickNode.cpp

moc_GlobeOsg.o: moc_GlobeOsg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GlobeOsg.o moc_GlobeOsg.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/myQmlOsg/bin || mkdir -p $(INSTALL_ROOT)/opt/myQmlOsg/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/myQmlOsg/bin/myQmlOsg.app
	
	-$(INSTALL_DIR) myQmlOsg.app $(INSTALL_ROOT)/opt/myQmlOsg/bin/myQmlOsg.app
	-$(STRIP) $(INSTALL_ROOT)/opt/myQmlOsg/bin/myQmlOsg.app/Contents/MacOS/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/myQmlOsg/bin/myQmlOsg.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/myQmlOsg/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

